# Generated by Django 4.2.3 on 2023-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
